version: '3'
services:
    backend:
        image: tag-backend
        ports: 
            - '3000:3000'
        build: 
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            - /app/node_modules 
            - ./backend-app:/app
    frontend: 
        image: tag-frontend
        ports: 
            -  '3001:3001'
        build: 
            dockerfile: Dockerfile
            context: ./frontend
        volumes:
            - /app/node_modules 
            - ./frontend-app:/app